runtime: python39
entrypoint: gunicorn -b :$PORT app:app  # Замените `app:app` на путь к вашему приложению

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'C:\\Users\\atala\\Downloads\\exalted-summer-438723-h7-7ed800381bf3.json'

